import type { ScanResult } from './types';

export const mockScanResults: Record<string, ScanResult> = {
  '9780743273565': {
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    category: 'Books',
    itemType: 'books',
    image: 'https://placehold.co/150x200/blue/white?text=Book',
    currentPrice: 12.99,
    suggestedPrice: 18.5,
    averagePrice: 15.75,
    salesRank: '#1,234 in Books',
    recommendation: 'keep',
    profit: 5.51,
    margin: '29.8%',
    priceHistory: '↑ 12% this month',
  },
  '047875815568': {
    title: 'Call of Duty: Modern Warfare II',
    publisher: 'Activision',
    category: 'Video Games',
    itemType: 'video_games',
    platform: 'PlayStation 5',
    image: 'https://placehold.co/150x200/blue/white?text=Game',
    currentPrice: 45.99,
    suggestedPrice: 52.0,
    averagePrice: 48.5,
    salesRank: '#23 in Video Games',
    recommendation: 'keep',
    profit: 6.01,
    margin: '11.6%',
    priceHistory: '↓ 5% this month',
  },
  '602527314563': {
    title: 'Taylor Swift - Folklore',
    publisher: 'Republic Records',
    category: 'Music',
    itemType: 'music',
    image: 'https://placehold.co/150x200/blue/white?text=Music',
    currentPrice: 18.99,
    suggestedPrice: 24.0,
    averagePrice: 21.50,
    salesRank: '#12 in Music',
    recommendation: 'keep',
    profit: 5.01,
    margin: '20.9%',
    priceHistory: '↑ 8% this month',
  },
  '786936294850': {
    title: 'Avatar: The Way of Water',
    publisher: '20th Century Studios',
    category: 'Movies & TV',
    itemType: 'videos',
    image: 'https://placehold.co/150x200/blue/white?text=Movie',
    currentPrice: 22.99,
    suggestedPrice: 19.0,
    averagePrice: 20.50,
    salesRank: '#45 in Movies',
    recommendation: 'discard',
    profit: -3.99,
    margin: '-17.4%',
    priceHistory: '↓ 15% this month',
  },
  '123456789012': {
    title: 'Generic Item',
    category: 'Other',
    itemType: 'other',
    image: 'https://placehold.co/150x200/gray/white?text=Item',
    currentPrice: 9.99,
    suggestedPrice: 12.0,
    averagePrice: 10.50,
    salesRank: '#567 in Other',
    recommendation: 'warn',
    profit: 2.01,
    margin: '20.1%',
    priceHistory: 'stable',
  },
};
